# -*- mode: dockerfile -*-
FROM docker.io/silex/emacs:29.1-ci-cask
RUN apt-get update && apt-get --assume-yes install \
    python3-pip \
    tmux \ 
    && rm /usr/lib/python*/EXTERNALLY-MANAGED \
    && python3 -m pip install --upgrade --upgrade-strategy=eager pip \
    && python3 -m pip install 'notebook<7' yq

COPY install-ein.el /opt/
RUN emacs -nw --batch --eval '(load "/opt/install-ein.el")'

### Install ein with unrelased commits
### ==================================
# RUN rm -r ~/.emacs.d/elpa/ein-*/ \
#     && git clone https://github.com/millejoh/emacs-ipython-notebook /build/ein \
#     && cd /build/ein && make install

COPY .tmux.conf /root/
